global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'playwright-server'
    static_configs:
      - targets: ['playwright-server:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'playwright-health'
    static_configs:
      - targets: ['playwright-server:8000']
    metrics_path: '/health'
    scrape_interval: 60s
    scrape_timeout: 5s